// Generated by AI (UnitTest MCP)

use ringmaster_backend::embedding_adapter::{embed, EmbeddingConfig};
use std::io::{Read, Write};
use std::net::TcpListener;
use std::sync::mpsc::{self, Receiver};
use std::thread::{self, JoinHandle};
use std::time::Duration;

fn spawn_embedding_server() -> (String, Receiver<String>, JoinHandle<()>) {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind test embedding server");
    let address = listener.local_addr().expect("read test server address");
    let (request_sender, request_receiver) = mpsc::channel();

    let handle = thread::spawn(move || {
        let (mut stream, _) = listener.accept().expect("accept embedding request");
        stream
            .set_read_timeout(Some(Duration::from_secs(5)))
            .expect("set request timeout");

        let mut request_bytes = Vec::new();
        let mut buffer = [0_u8; 4096];
        loop {
            let read = stream.read(&mut buffer).expect("read embedding request");
            if read == 0 {
                break;
            }
            request_bytes.extend_from_slice(&buffer[..read]);
            if request_bytes.windows(4).any(|window| window == b"\r\n\r\n") {
                break;
            }
        }

        request_sender
            .send(String::from_utf8_lossy(&request_bytes).into_owned())
            .expect("publish captured request");

        let body = r#"{"data":[{"embedding":[0.25,0.5]}]}"#;
        write!(
            stream,
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
            body.len(),
            body
        )
        .expect("write embedding response");
        stream.flush().expect("flush embedding response");
    });

    (format!("http://{address}"), request_receiver, handle)
}

async fn capture_request(api_key: Option<&str>) -> String {
    let (url, request_receiver, server_handle) = spawn_embedding_server();
    let config = EmbeddingConfig {
        url,
        model: "test-embedding-model".to_string(),
        api_key: api_key.map(str::to_string),
    };

    let embedding = embed(&config, "test input")
        .await
        .expect("embedding request succeeds");
    assert_eq!(embedding, vec![0.25, 0.5]);

    let request = request_receiver
        .recv_timeout(Duration::from_secs(5))
        .expect("receive captured request");
    server_handle.join().expect("join test embedding server");
    request
}

#[tokio::test]
async fn embed_sends_bearer_authorization_when_api_key_is_configured() {
    let request = capture_request(Some("test-token")).await;
    let headers = request.split("\r\n\r\n").next().expect("request headers");

    assert!(headers
        .lines()
        .any(|line| line.eq_ignore_ascii_case("authorization: Bearer test-token")));
}

#[tokio::test]
async fn embed_omits_authorization_when_api_key_is_absent() {
    let request = capture_request(None).await;
    let headers = request.split("\r\n\r\n").next().expect("request headers");

    assert!(!headers
        .lines()
        .any(|line| line.to_ascii_lowercase().starts_with("authorization:")));
}

#[test]
fn from_env_reads_a_non_blank_api_key_and_ignores_a_blank_one() {
    std::env::set_var(
        "RINGMASTER_EMBEDDING_URL",
        "https://embeddings.example.test/v1",
    );
    std::env::set_var("RINGMASTER_EMBEDDING_MODEL", "hosted-768");
    std::env::set_var("RINGMASTER_EMBEDDING_API_KEY", "configured-token");

    let configured = EmbeddingConfig::from_env().expect("embedding config is enabled");
    assert_eq!(configured.url, "https://embeddings.example.test/v1");
    assert_eq!(configured.model, "hosted-768");
    assert_eq!(configured.api_key.as_deref(), Some("configured-token"));

    std::env::set_var("RINGMASTER_EMBEDDING_API_KEY", "   ");
    let keyless = EmbeddingConfig::from_env().expect("keyless embedding config remains valid");
    assert_eq!(keyless.api_key, None);

    std::env::remove_var("RINGMASTER_EMBEDDING_URL");
    std::env::remove_var("RINGMASTER_EMBEDDING_MODEL");
    std::env::remove_var("RINGMASTER_EMBEDDING_API_KEY");
}
