// Generated by AI (UnitTest MCP)

use ringmaster_backend::graph;
use ringmaster_backend::transcript::{
    ingest_source, ingest_transcript, MeetingMetadata, SourceMetadata,
};
use serde_json::json;
use sqlx::postgres::PgPoolOptions;
use std::collections::HashSet;
use uuid::Uuid;

fn assert_test_database(database_url: &str) {
    let database_name = database_url
        .rsplit('/')
        .next()
        .map(|tail| tail.split(['?', '#']).next().unwrap_or(tail))
        .unwrap_or("");
    assert_eq!(
        database_name, "ringmaster_test",
        "refusing to run participant-linking tests against {database_name:?}"
    );
}

async fn test_pool() -> sqlx::PgPool {
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set to run participant-linking tests");
    assert_test_database(&database_url);
    PgPoolOptions::new()
        .max_connections(2)
        .connect(&database_url)
        .await
        .expect("connect to test database")
}

async fn participated_in_edges(pool: &sqlx::PgPool, source_id: Uuid) -> Vec<(Uuid, Option<f32>)> {
    sqlx::query_as(
        "SELECT from_id, confidence FROM edges WHERE to_id = $1 AND edge_type = 'participated_in'",
    )
    .bind(source_id)
    .fetch_all(pool)
    .await
    .expect("read participated_in edges")
}

#[tokio::test]
async fn ingest_source_links_exact_participant_and_speaker_matches_once_each() {
    let pool = test_pool().await;
    let marker = Uuid::new_v4();
    let participant_name = format!("Participant {marker}");
    let speaker_name = format!("Speaker {marker}");
    let participant_id = graph::create_node(&pool, "person", &participant_name, json!({}))
        .await
        .expect("create participant person");
    let speaker_id = graph::create_node(&pool, "person", &speaker_name, json!({}))
        .await
        .expect("create speaker person");

    let metadata = SourceMetadata {
        source_type: "meeting".to_string(),
        title: format!("Participant linking {marker}"),
        occurred_at: chrono::Utc::now(),
        participants: vec![
            participant_name.to_uppercase(),
            participant_name.to_lowercase(),
        ],
    };
    let raw_text = format!(
        "{}: First turn.\n{}: Second turn.",
        speaker_name.to_lowercase(),
        speaker_name.to_uppercase()
    );

    let ingested = ingest_source(&pool, &metadata, &raw_text)
        .await
        .expect("ingest meeting source");
    let edges = participated_in_edges(&pool, ingested.node_id).await;
    let linked_people: HashSet<Uuid> = edges.iter().map(|(person_id, _)| *person_id).collect();

    assert_eq!(
        edges.len(),
        2,
        "duplicate names must not create duplicate edges"
    );
    assert_eq!(linked_people, HashSet::from([participant_id, speaker_id]));
    assert!(edges.iter().all(|(_, confidence)| *confidence == Some(1.0)));
}

#[tokio::test]
async fn ingest_transcript_links_a_matching_person_in_the_same_legacy_path() {
    let pool = test_pool().await;
    let marker = Uuid::new_v4();
    let person_name = format!("Legacy Participant {marker}");
    let person_id = graph::create_node(&pool, "person", &person_name, json!({}))
        .await
        .expect("create legacy participant person");
    let metadata = MeetingMetadata {
        title: format!("Legacy participant linking {marker}"),
        occurred_at: Some(chrono::Utc::now()),
        organiser: None,
        participants: vec![person_name.to_uppercase()],
    };
    let raw_text = format!(
        "{}: The same person is also the speaker.",
        person_name.to_lowercase()
    );

    let ingested = ingest_transcript(&pool, &metadata, &raw_text)
        .await
        .expect("ingest legacy transcript");
    let edges = participated_in_edges(&pool, ingested.meeting_id).await;

    assert_eq!(edges, vec![(person_id, Some(1.0))]);
}

#[tokio::test]
async fn ingest_non_meeting_source_links_matching_participants_without_speakers() {
    let pool = test_pool().await;
    let marker = Uuid::new_v4();
    let person_name = format!("Email Participant {marker}");
    let person_id = graph::create_node(&pool, "person", &person_name, json!({}))
        .await
        .expect("create email participant person");
    let metadata = SourceMetadata {
        source_type: "email".to_string(),
        title: format!("Email participant linking {marker}"),
        occurred_at: chrono::Utc::now(),
        participants: vec![person_name.to_uppercase()],
    };

    let ingested = ingest_source(&pool, &metadata, "An email body without a speaker.")
        .await
        .expect("ingest email source");
    let edges = participated_in_edges(&pool, ingested.node_id).await;
    let (speaker,): (Option<String>,) =
        sqlx::query_as("SELECT speaker FROM source_fragments WHERE id = $1")
            .bind(ingested.fragment_ids[0])
            .fetch_one(&pool)
            .await
            .expect("read email fragment speaker");

    assert_eq!(edges, vec![(person_id, Some(1.0))]);
    assert_eq!(speaker, None);
}

#[tokio::test]
async fn unmatched_names_create_no_people_and_no_participation_edges() {
    let pool = test_pool().await;
    let marker = Uuid::new_v4();
    let participant_name = format!("Unmatched Participant {marker}");
    let speaker_name = format!("Unmatched Speaker {marker}");
    let metadata = SourceMetadata {
        source_type: "meeting".to_string(),
        title: format!("Unmatched participant linking {marker}"),
        occurred_at: chrono::Utc::now(),
        participants: vec![participant_name.clone()],
    };

    let ingested = ingest_source(
        &pool,
        &metadata,
        &format!("{speaker_name}: No matching person exists."),
    )
    .await
    .expect("ingest source with unmatched names");
    let edges = participated_in_edges(&pool, ingested.node_id).await;
    let (created_people,): (i64,) = sqlx::query_as(
        "SELECT COUNT(*) FROM nodes WHERE node_type = 'person' \
         AND (lower(canonical_text) = lower($1) OR lower(canonical_text) = lower($2))",
    )
    .bind(&participant_name)
    .bind(&speaker_name)
    .fetch_one(&pool)
    .await
    .expect("count unexpectedly created people");

    assert!(
        edges.is_empty(),
        "unmatched names must not create participated_in edges"
    );
    assert_eq!(
        created_people, 0,
        "unmatched names must not fabricate Person nodes"
    );
    assert_eq!(
        ingested.fragment_ids.len(),
        1,
        "ordinary ingestion must still succeed"
    );
}
