// Generated by AI (UnitTest MCP)
pub mod api;
pub mod audit;
pub mod embedding_adapter;
pub mod extraction;
pub mod graph;
pub mod model_adapter;
pub mod obligation;
pub mod synthesis;
pub mod transcript;

const ISOLATED_TEST_DATABASE: &str = "ringmaster_test";

fn database_name(database_url: &str) -> &str {
    database_url
        .rsplit('/')
        .next()
        .map(|tail| tail.split(['?', '#']).next().unwrap_or(tail))
        .unwrap_or("")
}

fn resolve_backend_bind_addr(configured: Option<String>) -> String {
    configured
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "0.0.0.0:8080".to_string())
}

/// Returns the normal backend bind address, with an opt-in override used by
/// ADR-0073's isolated Playwright server.
pub fn backend_bind_addr() -> String {
    resolve_backend_bind_addr(std::env::var("RINGMASTER_BIND_ADDR").ok())
}

fn enforce_test_database(database_url: &str, required: bool) -> Result<(), String> {
    if !required {
        return Ok(());
    }

    let actual = database_name(database_url);
    if actual == ISOLATED_TEST_DATABASE {
        Ok(())
    } else {
        Err(format!(
            "refusing test-mode backend startup against database {actual:?}; \
             DATABASE_URL must target {ISOLATED_TEST_DATABASE:?}"
        ))
    }
}

/// Refuses Playwright startup against the development database when
/// `RINGMASTER_REQUIRE_TEST_DATABASE=true` (ADR-0073). The check occurs before
/// opening a connection or applying migrations.
pub fn enforce_test_database_if_required(database_url: &str) -> Result<(), String> {
    let required = std::env::var("RINGMASTER_REQUIRE_TEST_DATABASE")
        .is_ok_and(|value| value.eq_ignore_ascii_case("true"));
    enforce_test_database(database_url, required)
}

// ADR-0057: backend unit tests share one Postgres server with the running dev
// stack. This guard makes test-database isolation enforced, not merely a
// documented convention (ADR-0056): every test_pool() calls it before
// connecting, and it panics unless DATABASE_URL targets the isolated
// ringmaster_test database -- so a stray run against the long-lived ringmaster
// database a person actually reads fails loudly instead of silently polluting it.
#[cfg(test)]
pub(crate) fn guard_test_database(database_url: &str) {
    let database_name = database_name(database_url);
    assert_eq!(
        database_name, ISOLATED_TEST_DATABASE,
        "refusing to run backend tests against database {database_name:?} \
         (DATABASE_URL={database_url:?}); tests must target {ISOLATED_TEST_DATABASE:?} \
         -- see ADR-0057 and docs/CONTRIBUTING.md"
    );
}

#[cfg(test)]
mod guard_tests {
    use super::{enforce_test_database, guard_test_database, resolve_backend_bind_addr};

    #[test]
    fn backend_bind_address_defaults_to_the_development_port() {
        assert_eq!(resolve_backend_bind_addr(None), "0.0.0.0:8080");
        assert_eq!(
            resolve_backend_bind_addr(Some("  ".to_string())),
            "0.0.0.0:8080"
        );
    }

    #[test]
    fn backend_bind_address_honors_a_non_blank_override() {
        assert_eq!(
            resolve_backend_bind_addr(Some("127.0.0.1:18080".to_string())),
            "127.0.0.1:18080"
        );
    }

    #[test]
    fn required_test_database_accepts_only_ringmaster_test() {
        assert_eq!(
            enforce_test_database(
                "postgres://ringmaster:ringmaster-dev@localhost:55432/ringmaster_test",
                true
            ),
            Ok(())
        );
        assert!(enforce_test_database(
            "postgres://ringmaster:ringmaster-dev@localhost:55432/ringmaster",
            true
        )
        .is_err());
    }

    #[test]
    fn optional_test_database_guard_leaves_normal_startup_unchanged() {
        assert_eq!(
            enforce_test_database(
                "postgres://ringmaster:ringmaster-dev@localhost:5432/ringmaster",
                false
            ),
            Ok(())
        );
    }

    #[test]
    fn guard_accepts_isolated_database() {
        guard_test_database("postgres://ringmaster:ringmaster-dev@postgres:5432/ringmaster_test");
        guard_test_database("postgres://u:p@localhost:5432/ringmaster_test?sslmode=require");
    }

    #[test]
    #[should_panic(expected = "refusing to run backend tests")]
    fn guard_rejects_dev_database() {
        guard_test_database("postgres://ringmaster:ringmaster-dev@postgres:5432/ringmaster");
    }
}
