// Generated by AI (UnitTest MCP)
import { test, expect, type Locator, type Page } from "@playwright/test";

// ADR-0059: People's "show everyone" view is now paginated (50 rows per
// page), so a single freshly-created test fixture can land past page one
// under concurrent load (other tests/sessions creating newer rows in the
// same shared database). Clicks "Load more" until the target is visible or
// no further pages remain, waiting for each page's fetch to actually land
// (not just the click) before deciding whether to click again.
async function revealByClickingLoadMore(page: Page, target: Locator): Promise<void> {
  const loadMore = page.getByRole("button", { name: "Load more", exact: true });
  const cards = page.locator(".people-card");
  for (let attempt = 0; attempt < 30; attempt += 1) {
    if (await target.isVisible()) return;
    if (!(await loadMore.isVisible())) break;
    const countBefore = await cards.count();
    await loadMore.click();
    await expect.poll(async () => cards.count()).toBeGreaterThan(countBefore);
  }
}

// ADR-0014: asserts real client-side rendering and interaction (tab
// switching, filtering), never specific row counts or content — the shared
// development Postgres volume accumulates data across sessions and agents.
// ADR-0022/ADR-0039: Today (formerly Daily Brief) is the default landing
// tab -- "start with Attention, not Work" (VISION.md).
test("today tab renders a ranked list by default", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("Today");
  await expect(page.locator("p.error")).toHaveCount(0);
});

// ADR-0084: proves the narrative summary reuses the existing date_compression
// and stale risk signals honestly -- a zero count for either is omitted
// entirely, never rendered as "0 ...". Mocks GET /api/daily-brief so the
// exact counts are deterministic regardless of whatever the shared
// development database currently contains.
test("today: narrative summary reports date_compression/stale counts and omits zero counts (ADR-0084)", async ({ page }) => {
  const unique = Date.now();
  await page.route("**/api/daily-brief", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify([
        {
          obligation_id: `00000000-0000-4000-a000-${String(unique).padStart(12, "0")}`,
          status: "at_risk",
          hard_due_at: null,
          soft_due_at: null,
          updated_at: new Date().toISOString(),
          reason: "date-compressed test item",
          source_fragment_id: null,
          source_text: null,
          risk_signals: [{ signal: "date_compression", explanation: "Due within 7 days." }],
        },
        {
          obligation_id: `00000000-0000-4000-a000-${String(unique + 1).padStart(12, "0")}`,
          status: "open",
          hard_due_at: null,
          soft_due_at: null,
          updated_at: new Date().toISOString(),
          reason: "stale test item",
          source_fragment_id: null,
          source_text: null,
          risk_signals: [{ signal: "stale", explanation: "No update recorded in 30 days." }],
        },
      ]),
    });
  });

  await page.goto("/");
  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");

  const summary = page.locator(".today-summary");
  await expect(summary.getByText("2 things need attention today.")).toBeVisible();
  await expect(summary.getByText("1 will become risk this week.")).toBeVisible();
  await expect(summary.getByText("1 commitment appears forgotten.")).toBeVisible();
  await expect(summary.getByText(/Good morning\.|Good afternoon\.|Good evening\./)).toBeVisible();
});

// ADR-0084: an empty daily brief keeps the pre-existing honest empty state
// and renders no narrative summary lines at all.
test("today: honest empty state renders no narrative summary when nothing needs attention (ADR-0084)", async ({ page }) => {
  await page.route("**/api/daily-brief", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify([]) });
  });

  await page.goto("/");
  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByText("Nothing needs your attention right now.")).toBeVisible();
  await expect(page.locator(".today-summary")).toHaveCount(0);
});

// ADR-0047: selecting a Today row opens the shared Obligation detail view,
// and Back returns to the list -- tolerant of whatever the shared
// development database currently contains (never asserting exact content).
test("obligation detail: selecting a Today row opens detail and Back returns", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");

  const row = page.locator(".daily-brief-row-button").first();
  test.skip((await row.count()) === 0, "no Today items exist yet to select");

  await row.click();
  await expect(page.locator(".obligation-detail")).toBeVisible();
  await expect(page.locator(".obligation-detail .today-item-title")).not.toHaveText("");

  await page.locator(".obligation-detail-back").click();
  await expect(page.locator(".daily-brief-list")).toBeVisible();
});

// ADR-0039: Obligations/Search/Graph are demoted to a secondary/developer
// group but remain fully reachable and functionally unchanged.
test("obligations tab renders a table backed by the backend API", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("tab", { name: "Obligations" }).click();
  await expect(page.getByRole("tab", { name: "Obligations" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("Obligations");
  await expect(page.locator("p.error")).toHaveCount(0);

  const headerCells = page.locator("table thead th");
  await expect(headerCells).toHaveText(["Obligation", "Status", "Updated"]);

  const rows = page.locator("table tbody tr");
  const rowCount = await rows.count();
  if (rowCount > 0) {
    const firstRowCells = rows.first().locator("td");
    await expect(firstRowCells).toHaveCount(3);
    for (const cell of await firstRowCells.all()) {
      await expect(cell).not.toHaveText("");
    }
  }
});

test("switching to the Inbox tab renders a different, real client-side view", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("tab", { name: "Inbox" }).click();

  await expect(page.getByRole("tab", { name: "Inbox" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("Inbox");

  const headerCells = page.locator("table thead th");
  const headerCount = await headerCells.count();
  if (headerCount > 0) {
    await expect(headerCells).toHaveText(["Type", "Statement", "Validation state", "Confidence", "Evidence", "Actions"]);
  }
});

test("filtering obligations by status only shows matching rows", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("tab", { name: "Obligations" }).click();

  // Wait for the async fetch to populate the table before reading filter options.
  await expect(page.locator("table tbody tr").first()).toBeVisible();

  const statusOptions = await page.locator("select").first().locator("option").allTextContents();
  const concreteStatus = statusOptions.find((option) => option !== "All");
  test.skip(!concreteStatus, "no obligations exist yet to filter by status");

  await page.locator("select").first().selectOption(concreteStatus!);

  const badges = page.locator("table tbody .badge");
  const badgeCount = await badges.count();
  for (let index = 0; index < badgeCount; index += 1) {
    // Badge text carries a leading status icon (ADR-0030), so match the status
    // name within the text rather than asserting an exact string.
    await expect(badges.nth(index)).toContainText(concreteStatus!);
  }
});

// ADR-0019: tolerant of whether RINGMASTER_EMBEDDING_URL is configured in
// this environment -- asserts search reaches a final rendered state
// (results, empty state, or a surfaced backend error), never a crash.
test("search tab submits a query and renders a final state", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("tab", { name: "Search" }).click();
  await expect(page.getByRole("tab", { name: "Search" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("Search");

  await page.getByPlaceholder("Search meeting evidence…").fill("transition plan");
  await page.getByRole("button", { name: "Search" }).click();

  await expect(page.getByRole("button", { name: "Search" })).toBeEnabled({ timeout: 15000 });
  const hasError = (await page.locator("p.error").count()) > 0;
  const hasEmptyState = (await page.locator("p.empty-state").count()) > 0;
  const hasResultRows = (await page.locator("table tbody tr").count()) > 0;
  expect(hasError || hasEmptyState || hasResultRows).toBe(true);
});

// ADR-0033: proves the client-side traversal trail can grow across two real
// edges and return to the root, entirely on top of the existing one-hop
// GET /api/nodes/:id primitive (no multi-hop backend route involved). Node
// type/text are kept short (<14 chars) and stamped with Date.now() so they
// (a) survive the radial view's label truncation and (b) stay unique against
// the shared development database and any concurrent agent session.
test("graph trail: traversing two edges and returning to the root (ADR-0033)", async ({ page }) => {
  const stamp = Date.now() % 100000;
  const nodeType = `trailtest${stamp}`;
  const nodeA = `Rt${stamp}`;
  const nodeB = `Md${stamp}`;
  const nodeC = `Lf${stamp}`;

  await page.goto("/");
  await page.getByRole("tab", { name: "Graph" }).click();
  await expect(page.getByRole("tab", { name: "Graph" })).toHaveAttribute("aria-selected", "true");

  async function createNode(text: string) {
    await page.getByPlaceholder("Node type (e.g. person, risk)").fill(nodeType);
    await page.getByPlaceholder("Canonical text (e.g. a name)").fill(text);
    await page.getByRole("button", { name: "Create node" }).click();
    await expect(page.locator(".node-detail h3")).toContainText(text);
  }

  async function selectNode(text: string) {
    await page.locator(".node-list-button", { hasText: text }).click();
    await expect(page.locator(".node-detail h3")).toContainText(text);
  }

  async function link(fromText: string, toText: string, verb: string) {
    await selectNode(fromText);
    await page.locator(".node-detail select.link-target-select").selectOption({ label: `${nodeType}: ${toText}` });
    await page.getByPlaceholder("Relationship (e.g. made, owns)").fill(verb);
    await page.getByRole("button", { name: "Add relationship" }).click();
    // The form resets its fields on success (so the submit button goes back to
    // disabled by design, not because the request is stuck) -- the real proof
    // of success is the new neighbor appearing in the radial view.
    await expect(page.locator("svg.relationship-view g", { hasText: toText })).toBeVisible();
  }

  // Three fresh nodes, linked A -> B -> C, so the trail has two real edges to cross.
  await createNode(nodeA);
  await createNode(nodeB);
  await createNode(nodeC);
  await link(nodeA, nodeB, "leads_to");
  await link(nodeB, nodeC, "leads_to");

  // Start a fresh trail at the root: selecting from the node list always
  // begins a new trail (ADR-0033), so this is exactly one item.
  await selectNode(nodeA);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(1);
  await expect(page.locator(".graph-trail-back")).toBeDisabled();

  // Hop 1: click B's neighbor circle from A's radial view.
  await page.locator("svg.relationship-view g", { hasText: nodeB }).locator("circle.relationship-node-clickable").click();
  await expect(page.locator(".node-detail h3")).toContainText(nodeB);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(2);
  await expect(page.locator(".why-here")).toContainText(nodeA);
  await expect(page.locator(".why-here")).toContainText("leads_to");

  // Hop 2: from B, click specifically C's circle (B also neighbors A, so scope by C's label).
  await page.locator("svg.relationship-view g", { hasText: nodeC }).locator("circle.relationship-node-clickable").click();
  await expect(page.locator(".node-detail h3")).toContainText(nodeC);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(3);

  // The breadcrumb is a readable path: every node and the traversed verb appear in order.
  const trailText = await page.locator(".graph-trail-path").innerText();
  expect(trailText).toContain(nodeA);
  expect(trailText).toContain(nodeB);
  expect(trailText).toContain(nodeC);
  expect(trailText).toContain("leads_to");

  // Returning to the root via the dedicated Back control, one edge at a time.
  await page.locator(".graph-trail-back").click();
  await expect(page.locator(".node-detail h3")).toContainText(nodeB);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(2);

  await page.locator(".graph-trail-back").click();
  await expect(page.locator(".node-detail h3")).toContainText(nodeA);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(1);
  await expect(page.locator(".graph-trail-back")).toBeDisabled();
});

// ADR-0081: proves the Actions lens filters the radial neighbourhood down to
// what needs doing (an Obligation or a risk node), states the shown/
// filtered count honestly rather than silently hiding neighbours, and never
// disturbs the trail/pivot mechanism ADR-0033 already built.
test("graph explorer: the Actions lens filters neighbours to what needs doing (ADR-0081)", async ({ page }) => {
  const stamp = Date.now() % 100000;
  const nodeType = `lenstest${stamp}`;
  const root = `Rt${stamp}`;
  const riskNode = `Rk${stamp}`;
  const otherNode = `Ot${stamp}`;

  await page.goto("/");
  await page.getByRole("tab", { name: "Graph" }).click();
  await expect(page.getByRole("tab", { name: "Graph" })).toHaveAttribute("aria-selected", "true");

  async function createNode(text: string, type: string) {
    await page.getByPlaceholder("Node type (e.g. person, risk)").fill(type);
    await page.getByPlaceholder("Canonical text (e.g. a name)").fill(text);
    await page.getByRole("button", { name: "Create node" }).click();
    await expect(page.locator(".node-detail h3")).toContainText(text);
  }

  async function selectNode(text: string) {
    await page.locator(".node-list-button", { hasText: text }).click();
    await expect(page.locator(".node-detail h3")).toContainText(text);
  }

  async function link(fromText: string, toText: string, toType: string, verb: string) {
    await selectNode(fromText);
    await page.locator(".node-detail select.link-target-select").selectOption({ label: `${toType}: ${toText}` });
    await page.getByPlaceholder("Relationship (e.g. made, owns)").fill(verb);
    await page.getByRole("button", { name: "Add relationship" }).click();
    await expect(page.locator("svg.relationship-view g", { hasText: toText })).toBeVisible();
  }

  // A root plus one risk neighbour (actionable) and one same-freeform-type
  // neighbour (not actionable) -- proves the filter includes/excludes by
  // node_type, not by presence alone.
  await createNode(root, nodeType);
  await createNode(riskNode, "risk");
  await createNode(otherNode, nodeType);
  await link(root, riskNode, "risk", "at_risk_from");
  await link(root, otherNode, nodeType, "relates_to");

  // Default "All" lens: both neighbours render.
  await expect(page.locator("svg.relationship-view g", { hasText: riskNode })).toBeVisible();
  await expect(page.locator("svg.relationship-view g", { hasText: otherNode })).toBeVisible();
  await expect(page.locator(".relationship-count")).toContainText("2 relationships");
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(1);

  // Switching to "Actions" keeps only the risk neighbour and states the
  // shown/filtered count honestly, without touching the trail.
  await page.locator(".lens-select").selectOption("actions");
  await expect(page.locator("svg.relationship-view g", { hasText: riskNode })).toBeVisible();
  await expect(page.locator("svg.relationship-view g", { hasText: otherNode })).toHaveCount(0);
  await expect(page.locator(".relationship-count")).toHaveText("1 shown, 1 filtered by Actions lens");
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(1);

  // Pivoting into the still-visible risk neighbour works identically with the lens active.
  await page.locator("svg.relationship-view g", { hasText: riskNode }).locator("circle.relationship-node-clickable").click();
  await expect(page.locator(".node-detail h3")).toContainText(riskNode);
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(2);

  // Switching back to "All" does not reset or truncate the trail.
  await page.locator(".lens-select").selectOption("all");
  await expect(page.locator(".graph-trail-path .graph-trail-item")).toHaveCount(2);
});

// ADR-0035: proves the Buckets/Timeline toggle and the timeline's Now/zoom/
// pan/legend controls work as real client-side interactions on top of the
// existing GET /api/time-horizon response -- tolerant of whatever the
// shared development database currently contains, never asserting exact
// counts or specific obligations.
test("time horizon: switching to Timeline view exposes Now/zoom/pan controls (ADR-0035)", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("tab", { name: "Timeline" }).click();
  await expect(page.getByRole("tab", { name: "Timeline" })).toHaveAttribute("aria-selected", "true");

  // The GET /api/time-horizon fetch is kicked off once on initial mount
  // (App.tsx's load() awaits five endpoints together via Promise.all), not
  // on tab click, so wait for it to settle before deciding whether real data
  // exists. A transient failure on *any* of those five fetches rejects the
  // whole batch and renders p.error instead of ever populating timeHorizon --
  // tolerate that the same way the existing search-tab test tolerates a
  // surfaced backend error, rather than hanging or misreading it as "empty".
  await expect
    .poll(async () => (await page.locator(".time-horizon-view-toggle, p.empty-state, p.error").count()) > 0, { timeout: 15000 })
    .toBe(true);
  const hasError = (await page.locator("p.error").count()) > 0;
  test.skip(hasError, "backend fetch failed transiently for this run");
  const hasViewToggle = (await page.locator(".time-horizon-view-toggle").count()) > 0;
  test.skip(!hasViewToggle, "no obligations due within the horizon yet, so the view toggle doesn't render");

  await page.getByRole("button", { name: "Timeline" }).click();
  await expect(page.locator(".time-horizon-timeline")).toBeVisible();

  const totalBands = await page.locator(".time-horizon-band").count();
  expect(totalBands).toBeGreaterThan(0);

  // Zoom in focuses exactly one band; zoom out restores every band.
  await page.getByRole("button", { name: "Zoom in" }).click();
  await expect(page.locator(".time-horizon-band")).toHaveCount(1);
  await page.getByRole("button", { name: "Zoom out" }).click();
  await expect(page.locator(".time-horizon-band")).toHaveCount(totalBands);

  // Pan moves which band is focused, without changing how many bands render.
  const panNext = page.getByRole("button", { name: "Focus later window" });
  if (await panNext.isEnabled()) {
    await panNext.click();
    await expect(page.locator(".time-horizon-band")).toHaveCount(totalBands);
  }

  // Now deterministically resets focus back to the Overdue band.
  await page.getByRole("button", { name: "Now" }).click();
  await expect(page.locator(".time-horizon-band-focused")).toHaveClass(/accent-overdue/);

  // The legend toggle reveals the same accent chips the Buckets ribbon already uses.
  await page.getByRole("button", { name: "Show legend" }).click();
  await expect(page.locator(".time-horizon-legend .time-horizon-chip").first()).toBeVisible();

  // Expanding a marker, if one exists, reveals its evidence-backed reason inline.
  const marker = page.locator(".time-horizon-marker").first();
  if (await marker.count()) {
    await marker.click();
    await expect(page.locator(".time-horizon-marker-detail .daily-brief-reason").first()).toBeVisible();
  }

  // Switching back to Buckets is the "close" affordance -- the original list view returns.
  await page.getByRole("button", { name: "Buckets" }).click();
  await expect(page.locator(".time-horizon-timeline")).toHaveCount(0);
  await expect(page.locator(".time-horizon-sections")).toBeVisible();
});

// ADR-0039: proves the primary/secondary tab regrouping is real (Today,
// Timeline, People, Inbox as primary; Obligations, Search, Meetings,
// Activity still present, just visually demoted) -- not that the old tabs
// were deleted. Meetings joined the secondary group later (ADR-0043),
// Activity later still (ADR-0049). ADR-0080 promotes Graph to primary,
// after it: its progressive traversal trail (ADR-0033) now answers a
// primary management question, not a database-browser one.
test("primary navigation is Today/Timeline/People/Inbox/Graph; Obligations/Search remain as secondary tabs (ADR-0080)", async ({ page }) => {
  await page.goto("/");

  const tabs = page.getByRole("tab");
  await expect(tabs).toHaveText(["Today", "Timeline", "People", "Inbox", "Graph", "Obligations", "Search", "Meetings", "Activity"]);

  const secondaryTabs = page.locator(".tab-secondary");
  await expect(secondaryTabs).toHaveText(["Obligations", "Search", "Meetings", "Activity"]);
});

test("primary navigation scrolls internally without widening a narrow viewport", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");

  const tabList = page.getByRole("tablist", { name: "Views" });
  const tabListWidths = await tabList.evaluate((element) => ({
    client: element.clientWidth,
    scroll: element.scrollWidth,
  }));
  expect(tabListWidths.scroll).toBeGreaterThan(tabListWidths.client);

  const documentWidths = await page.evaluate(() => ({
    client: document.documentElement.clientWidth,
    scroll: document.documentElement.scrollWidth,
  }));
  expect(documentWidths.scroll).toBeLessThanOrEqual(documentWidths.client);

  const activity = page.getByRole("tab", { name: "Activity", exact: true });
  await activity.scrollIntoViewIfNeeded();
  await activity.click();
  await expect(activity).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("Activity");
});

// ADR-0039: People is a first-class primary tab over already-existing data
// (GET /api/nodes?node_type=person, GET /api/nodes/:id) -- not a new route.
// ADR-0051: People defaults to who-needs-attention; a bare person with no
// linked Obligations only appears after switching to "Show everyone".
// ADR-0059: grouped as `serial` -- the "Load more" test below seeds 51 new
// person nodes, and under this suite's default `fullyParallel` execution
// that insert burst can race the other two tests' single-fixture lookups
// (offset pagination ordered by updated_at can skip a row while concurrent
// writes keep shifting the ranking, an accepted trade-off named in
// ADR-0059 itself). Serial execution removes the temporal overlap instead
// of just retrying harder.
test.describe.serial("People tab", () => {
test("people tab opens a person into relationship and populated interaction detail", async ({ page, request, baseURL }) => {
  const unique = Date.now();
  const personName = `Recent Interaction Person ${unique}`;
  const sourceTitle = `Recent Interaction Note ${unique}`;
  const occurredAt = new Date(Date.now() - 86_400_000).toISOString();

  const personResponse = await request.post(`${baseURL}/api/nodes`, {
    data: { node_type: "person", canonical_text: personName },
  });
  expect(personResponse.ok()).toBe(true);

  const sourceResponse = await request.post(`${baseURL}/api/sources/ingest`, {
    data: {
      source_type: "note",
      title: sourceTitle,
      occurred_at: occurredAt,
      participants: [personName],
      text: `Interaction evidence ${unique}`,
    },
  });
  expect(sourceResponse.ok()).toBe(true);
  const source = (await sourceResponse.json()) as { node_id: string };

  await page.goto("/");
  await page.getByRole("tab", { name: "People" }).click();
  await expect(page.getByRole("tab", { name: "People" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("h1")).toHaveText("People");

  await page.getByRole("button", { name: "Show everyone" }).click();
  const target = page.getByRole("button", { name: new RegExp(personName) });
  await revealByClickingLoadMore(page, target);
  await expect(target).toBeVisible();
  await target.click();
  await expect(page.locator(".people-detail h3")).toHaveText(personName);
  const interactions = page.getByRole("region", { name: "Recent interactions" });
  await expect(interactions.getByText(sourceTitle)).toBeVisible();
  await expect(interactions.locator(".recent-interaction-meta")).toContainText("note");
  const expectedDate = await page.evaluate((value) => new Date(value).toLocaleDateString(), occurredAt);
  await expect(interactions.locator(".recent-interaction-meta")).toContainText(expectedDate);
  await expect(interactions).not.toContainText(source.node_id);
  await expect(interactions).not.toContainText("participated_in");
  await expect(page.locator(".relationship-obligations")).toBeVisible();

  await page.getByRole("button", { name: "All people" }).click();
  await expect(page.locator(".people-list")).toBeVisible();
});

// ADR-0051: a bare person with no linked Obligations is excluded from the
// default (needs-attention) list until "Show everyone" is toggled on.
test("people tab defaults to who-needs-attention, excluding a person with no open obligations (ADR-0051)", async ({ page, request, baseURL }) => {
  const unique = Date.now();
  const bareName = `Needs Attention Filter Bare ${unique}`;

  const bareResponse = await request.post(`${baseURL}/api/nodes`, { data: { node_type: "person", canonical_text: bareName } });
  expect(bareResponse.ok()).toBe(true);

  await page.goto("/");
  await page.getByRole("tab", { name: "People" }).click();

  // The bare person (no linked Obligation at all) must not appear by default.
  await expect(page.getByRole("button", { name: new RegExp(bareName) })).toHaveCount(0);

  await page.getByRole("button", { name: "Show everyone" }).click();
  const bareTarget = page.getByRole("button", { name: new RegExp(bareName) });
  await revealByClickingLoadMore(page, bareTarget);
  await expect(bareTarget).toBeVisible();
  await bareTarget.click();
  const interactions = page.getByRole("region", { name: "Recent interactions" });
  await expect(interactions.getByText("No recorded interactions.")).toBeVisible();
  await page.getByRole("button", { name: "All people" }).click();
});

test("people detail reports a capped recent-interactions list honestly (ADR-0071)", async ({ page, request, baseURL }) => {
  const unique = Date.now();
  const personName = `Capped Recent Interactions Person ${unique}`;
  const personResponse = await request.post(`${baseURL}/api/nodes`, {
    data: { node_type: "person", canonical_text: personName },
  });
  expect(personResponse.ok()).toBe(true);
  const person = (await personResponse.json()) as { id: string };
  const recentInteractions = Array.from({ length: 10 }, (_, index) => ({
    source_id: `00000000-0000-4000-8000-${String(index).padStart(12, "0")}`,
    source_type: "note",
    title: `Capped interaction ${index + 1}`,
    occurred_at: new Date(Date.now() - index * 86_400_000).toISOString(),
    evidence_mode: "participated_in",
  }));

  await page.route(`**/api/nodes/${person.id}`, async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        id: person.id,
        node_type: "person",
        canonical_text: personName,
        attributes: {},
        lifecycle_state: "active",
        neighbors: [],
        relationship: null,
        last_interaction_at: recentInteractions[0].occurred_at,
        recent_interactions: recentInteractions,
        recent_interactions_total: 12,
      }),
    });
  });

  await page.goto("/");
  await page.getByRole("tab", { name: "People" }).click();
  await page.getByRole("button", { name: "Show everyone" }).click();
  const target = page.getByRole("button", { name: new RegExp(personName) });
  await revealByClickingLoadMore(page, target);
  await target.click();

  const interactions = page.getByRole("region", { name: "Recent interactions" });
  await expect(interactions.locator(".recent-interactions-list > li")).toHaveCount(10);
  await expect(interactions.getByText("Capped interaction 1", { exact: true })).toBeVisible();
  await expect(interactions.getByText("Showing the latest 10 of 12.")).toBeVisible();
});

// ADR-0059: proves "Load more" actually fetches and appends a further page
// rather than just being present but inert. Seeds 51 fresh person nodes
// (one more than the frontend's LIST_PAGE_SIZE of 50) via the existing
// POST /api/nodes route -- nodes sort newest-updated-first (graph.rs's
// `ORDER BY updated_at DESC`), so these occupy page one and guarantee a
// "Load more" affordance regardless of whatever else the shared
// development database currently contains.
test("people tab: Load more appends a further page (ADR-0059)", async ({ page, request, baseURL }) => {
  const unique = Date.now();
  await Promise.all(
    Array.from({ length: 51 }, (_, index) =>
      request.post(`${baseURL}/api/nodes`, { data: { node_type: "person", canonical_text: `Pagination Test Person ${unique}-${index}` } }),
    ),
  );

  await page.goto("/");
  await page.getByRole("tab", { name: "People" }).click();
  await page.getByRole("button", { name: "Show everyone" }).click();

  const cards = page.locator(".people-card");
  await expect(cards.first()).toBeVisible();
  const countBeforeLoadMore = await cards.count();

  const loadMore = page.getByRole("button", { name: "Load more", exact: true });
  await expect(loadMore).toBeVisible();
  await loadMore.click();

  await expect.poll(async () => cards.count()).toBeGreaterThan(countBeforeLoadMore);
});

}); // end test.describe.serial("People tab")

// ADR-0041: proves Risk Engine v1's signals, when present, actually render
// as real text in the browser -- tolerant of whatever the shared
// development database currently contains, never asserting a specific
// obligation or count. Checks the Timeline tab's (uncapped) Buckets view
// rather than Today's capped top-10 list, since a risk signal is far more
// likely to appear somewhere across every overdue/upcoming Obligation than
// within just the ten items Today happens to rank highest.
test("time horizon buckets show risk-signal explanations when any obligation has one (ADR-0041)", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("tab", { name: "Timeline" }).click();
  await expect(page.getByRole("tab", { name: "Timeline" })).toHaveAttribute("aria-selected", "true");

  await expect
    .poll(async () => (await page.locator(".time-horizon-sections, p.empty-state, p.error").count()) > 0, { timeout: 15000 })
    .toBe(true);
  const hasError = (await page.locator("p.error").count()) > 0;
  test.skip(hasError, "backend fetch failed transiently for this run");

  const hasRiskSignal = (await page.locator(".risk-signals li").count()) > 0;
  test.skip(!hasRiskSignal, "no Obligation currently due or overdue has any risk signal");

  // ADR-0046/ADR-0054 added the unowned/isolated signals after this test was
  // originally written for date_compression/stale alone -- risk_signals is an
  // array, so any of the four may legitimately be first.
  const explanation = await page.locator(".risk-signals li").first().textContent();
  expect(explanation).toMatch(/no evidence linked|no update in \d+ day\(s\)|no owner linked|not linked to anyone or anything/i);
});

// ADR-0043: proves the Meeting Review page renders an ingested meeting's
// transcript and can trigger extraction on a fragment with nothing
// extracted yet. Ingests its own meeting via the existing atomic ingestion
// route (ADR-0040) rather than the UI, since ingestion is deliberately an
// API/CLI/MCP action, not a page in this app (ADR-0034/0043). Tolerant of
// whether a model is configured in this environment -- either a real
// candidate appears or an honest "nothing worth extracting"/"no model
// configured" message renders, never a crash or a fabricated result.
test("meeting review: viewing a meeting and triggering extraction on a fragment (ADR-0043)", async ({ page, request }) => {
  const stamp = Date.now();
  const title = `Meeting Review Test ${stamp}`;
  const ingestResponse = await request.post("/api/sources/ingest", {
    data: {
      source_type: "meeting",
      title,
      occurred_at: new Date().toISOString(),
      participants: ["Roopa"],
      text: `Roopa: this is a unique test passage ${stamp} about a transition plan.`,
    },
  });
  expect(ingestResponse.ok()).toBeTruthy();

  await page.goto("/");
  await page.getByRole("tab", { name: "Meetings" }).click();
  await expect(page.getByRole("tab", { name: "Meetings" })).toHaveAttribute("aria-selected", "true");

  await page.locator(".node-list-button", { hasText: title }).click();
  await expect(page.locator(".meeting-review-detail h3")).toHaveText(title);
  await expect(page.locator(".meeting-fragment").first()).toContainText(`test passage ${stamp}`);

  await page.locator(".meeting-fragment", { hasText: `test passage ${stamp}` }).getByRole("button", { name: "Extract" }).click();

  // A real LLM call, not a fixed computation -- generous timeout, especially
  // under concurrent multi-agent load against the same local model server.
  await expect(page.locator(".meeting-candidate-row, .meeting-review-extract-message").first()).toBeVisible({ timeout: 45000 });
});

// ADR-0045: proves the Correct control genuinely edits a candidate's type
// and/or statement and transitions it to "corrected" -- tolerant of
// whatever the shared development database currently contains, never
// asserting a specific candidate or count.
test("inbox tab: correcting a candidate edits its statement and shows Corrected (ADR-0045)", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("tab", { name: "Inbox" }).click();
  await expect(page.getByRole("tab", { name: "Inbox" })).toHaveAttribute("aria-selected", "true");

  const correctButton = page.locator(".correct-button").first();
  test.skip((await correctButton.count()) === 0, "no candidate is currently in the candidate state to correct");

  await correctButton.click();
  const stamp = Date.now();
  const correctedStatement = `corrected via Playwright ${stamp}`;
  await page.locator(".correction-form textarea").fill(correctedStatement);
  await page.locator(".save-correction-button").click();

  const row = page.locator("tr", { has: page.getByText(correctedStatement) });
  await expect(row).toBeVisible();
  // ADR-0076 added a leading select-checkbox column, shifting this index.
  await expect(row.locator("td").nth(3)).toHaveText("corrected");
  await expect(row.getByRole("button", { name: "Promote to Obligation" })).toBeVisible();
});

// ADR-0076: proves bulk select + Accept transitions multiple candidates in
// one request -- via its own POST /api/candidates/batch call, not N calls
// to the single-item accept route. Mocks GET/POST so it's deterministic
// regardless of whatever the shared development database currently holds.
test("inbox tab: bulk-select and Accept transitions multiple candidates in one request (ADR-0076)", async ({ page }) => {
  const unique = Date.now();
  const candidates = Array.from({ length: 3 }, (_, index) => ({
    candidate_id: `10000000-0000-4000-9000-${String(unique + index).padStart(12, "0")}`,
    candidate_type: "decision",
    statement: `Bulk triage candidate ${unique}-${index}`,
    validation_state: "candidate",
    confidence: 0.9,
    source_fragment_id: null as string | null,
    promoted_obligation_id: null as string | null,
    source_text: null as string | null,
    speaker: null as string | null,
  }));

  let batchRequestBody: { candidate_ids: string[]; action: string } | null = null;
  await page.route("**/api/candidates?**", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(candidates) });
  });
  await page.route("**/api/candidates/batch", async (route) => {
    batchRequestBody = route.request().postDataJSON();
    const acceptedIds = new Set(batchRequestBody!.candidate_ids);
    const updated = candidates.filter((c) => acceptedIds.has(c.candidate_id));
    for (const candidate of updated) candidate.validation_state = "accepted";
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ updated, errors: [] }),
    });
  });

  await page.goto("/");
  await page.getByRole("tab", { name: "Inbox" }).click();
  await expect(page.getByText(`Bulk triage candidate ${unique}-0`)).toBeVisible();

  await page.getByLabel(`Select candidate: Bulk triage candidate ${unique}-0`).check();
  await page.getByLabel(`Select candidate: Bulk triage candidate ${unique}-1`).check();
  await expect(page.getByText("2 selected", { exact: true })).toBeVisible();

  await page.getByRole("button", { name: "Accept 2 selected" }).click();

  await expect.poll(() => batchRequestBody?.action).toBe("accept");
  expect(batchRequestBody?.candidate_ids).toHaveLength(2);

  const firstRow = page.locator("tr", { has: page.getByText(`Bulk triage candidate ${unique}-0`, { exact: true }) });
  await expect(firstRow.locator("td").nth(3)).toHaveText("accepted");
  const untouchedRow = page.locator("tr", { has: page.getByText(`Bulk triage candidate ${unique}-2`, { exact: true }) });
  await expect(untouchedRow.locator("td").nth(3)).toHaveText("candidate");
});

// ADR-0077: proves bulk-select and Promote creates Obligations for multiple
// accepted candidates in one request -- completing the triage loop
// ADR-0076 started (Accept alone never made a candidate actionable).
test("inbox tab: bulk-select and Promote creates Obligations for multiple accepted candidates in one request (ADR-0077)", async ({
  page,
}) => {
  const unique = Date.now();
  const candidates = Array.from({ length: 2 }, (_, index) => ({
    candidate_id: `20000000-0000-4000-9000-${String(unique + index).padStart(12, "0")}`,
    candidate_type: "commitment",
    statement: `Bulk promote candidate ${unique}-${index}`,
    validation_state: "accepted",
    confidence: 0.85,
    source_fragment_id: null as string | null,
    promoted_obligation_id: null as string | null,
    source_text: null as string | null,
    speaker: null as string | null,
  }));

  let batchPromoteRequestBody: { candidate_ids: string[] } | null = null;
  await page.route("**/api/candidates?**", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(candidates) });
  });
  await page.route("**/api/candidates/batch-promote", async (route) => {
    batchPromoteRequestBody = route.request().postDataJSON();
    const promotedIds = new Set(batchPromoteRequestBody!.candidate_ids);
    const promoted = candidates
      .filter((c) => promotedIds.has(c.candidate_id))
      .map((c, index) => {
        c.validation_state = "promoted";
        c.promoted_obligation_id = `30000000-0000-4000-9000-${String(unique + index).padStart(12, "0")}`;
        return {
          obligation_id: c.promoted_obligation_id,
          status: "open",
          updated_at: new Date().toISOString(),
          hard_due_at: null,
          soft_due_at: null,
          source_fragment_id: null,
          source_text: null,
        };
      });
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ promoted, errors: [] }),
    });
  });

  await page.goto("/");
  await page.getByRole("tab", { name: "Inbox" }).click();
  await expect(page.getByText(`Bulk promote candidate ${unique}-0`)).toBeVisible();

  await page.getByLabel(`Select candidate: Bulk promote candidate ${unique}-0`).check();
  await page.getByLabel(`Select candidate: Bulk promote candidate ${unique}-1`).check();
  await expect(page.getByText("2 selected", { exact: true })).toBeVisible();

  await page.getByRole("button", { name: "Promote 2 selected" }).click();

  await expect.poll(() => batchPromoteRequestBody?.candidate_ids.length).toBe(2);

  const firstRow = page.locator("tr", { has: page.getByText(`Bulk promote candidate ${unique}-0`, { exact: true }) });
  await expect(firstRow.locator("td").nth(3)).toHaveText("promoted");
});

// ADR-0049: proves the Activity tab surfaces a real, just-recorded audit
// row -- seeds its own marker via the Correct action rather than relying
// on whatever the shared development database already contains. Tolerant
// of the feed's 200-row cap: under this repo's own heavy concurrent write
// load, enough other audit rows can land between the write and the read
// to push the marker out of the capped window -- a real trade-off ADR-0049
// itself accepted, not a bug in the feature.
test("activity tab shows a just-recorded correction (ADR-0049)", async ({ page, request }) => {
  await page.goto("/");
  await page.getByRole("tab", { name: "Inbox" }).click();

  const correctButton = page.locator(".correct-button").first();
  test.skip((await correctButton.count()) === 0, "no candidate is currently in the candidate state to correct");

  await correctButton.click();
  const stamp = Date.now();
  const marker = `activity feed marker ${stamp}`;
  await page.locator(".correction-form textarea").fill(marker);
  await page.locator(".save-correction-button").click();
  await expect(page.getByText(marker)).toBeVisible();

  const auditResponse = await request.get("/api/audit-events?limit=200");
  expect(auditResponse.ok()).toBeTruthy();
  const auditEvents = (await auditResponse.json()) as { new_state: { statement?: string } | null }[];
  const foundInFeed = auditEvents.some((event) => event.new_state?.statement === marker);
  test.skip(!foundInFeed, "too many other audit rows landed in the 200-row window under concurrent load this run");

  await page.getByRole("tab", { name: "Activity" }).click();
  await expect(page.getByRole("tab", { name: "Activity" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator(".activity-states").filter({ hasText: marker }).first()).toBeVisible();
});

// ADR-0053: proves "What am I forgetting?" renders on Today, above "Do
// these together", and either lists real flagged Obligations (composing
// the existing risk_signals Daily Brief already returns, capped to 5) or
// an honest empty state -- never a fabricated reassurance. Tolerant of
// whatever the shared development database currently contains.
test("today: 'What am I forgetting?' shows flagged obligations or an honest empty state (ADR-0053)", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");

  const heading = page.getByRole("heading", { name: "What am I forgetting?" });
  await expect(heading).toBeVisible();

  const section = page.locator("h2:text('What am I forgetting?') + div.card");
  await expect(section).toBeVisible();

  const rows = section.locator(".daily-brief-list > li");
  const rowCount = await rows.count();
  if (rowCount === 0) {
    await expect(section.locator("p.empty-state")).toHaveText("Nothing flagged right now.");
    return;
  }

  expect(rowCount).toBeLessThanOrEqual(5);
  await expect(rows.first().locator(".risk-signals li").first()).toBeVisible();
});

// ADR-0084: the narrative summary above the ranked list is a time-of-day
// greeting plus honest, zero-omitted counts derived from data already
// fetched -- never asserts an exact count, since the shared database
// accumulates data across sessions/agents (same posture as ADR-0014's own
// "today tab renders a ranked list" test above).
// playwright-proves-today-narrative-summary
test("today: narrative summary shows a time-of-day greeting and honest, zero-omitted counts (ADR-0084)", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("tab", { name: "Today" })).toHaveAttribute("aria-selected", "true");

  const emptyState = page.getByText("Nothing needs your attention right now.");
  if (await emptyState.isVisible()) {
    await expect(page.locator(".today-summary")).toHaveCount(0);
    return;
  }

  const summary = page.locator(".today-summary");
  await expect(summary).toBeVisible();

  const greeting = summary.locator("p.today-greeting");
  await expect(greeting).toHaveText(/^Good (morning|afternoon|evening)\.$/);

  const summaryLines = summary.locator("p.today-summary-line");
  await expect(summaryLines.first()).toHaveText(/^\d+ things? needs? attention today\.$/);

  // Any additional lines are exactly the "will become risks"/"appear
  // forgotten" stats -- never a literal "0 ..." line (the honest
  // zero-omission rule ADR-0084 decides).
  const lineCount = await summaryLines.count();
  for (let index = 1; index < lineCount; index += 1) {
    await expect(summaryLines.nth(index)).toHaveText(
      /^\d+ (will become risks? this week\.|commitments? appears? forgotten\.)$/,
    );
  }
});
